const SIGN_IN_WITH_PHONE_SSO_ACTION = "SIGN_IN_WITH_PHONE_SSO_ACTION";
const SIGN_IN_WITH_PHONE_SSO_STARTED = "SIGN_IN_WITH_PHONE_SSO_STARTED";
const SIGN_IN_WITH_PHONE_SSO_SUCCEED = "SIGN_IN_WITH_PHONE_SSO_SUCCEED";
const SIGN_IN_WITH_PHONE_SSO_FAILD = "SIGN_IN_WITH_PHONE_SSO_FAILD";

const VERIFY_WITH_PHONE_SSO_ACTION = "VERIFY_WITH_PHONE_SSO_ACTION";
const VERIFY_WITH_PHONE_SSO_STARTED = "VERIFY_WITH_PHONE_SSO_STARTED";
const VERIFY_WITH_PHONE_SSO_SUCCEED = "VERIFY_WITH_PHONE_SSO_SUCCEED";
const VERIFY_WITH_PHONE_SSO_FAILD = "VERIFY_WITH_PHONE_SSO_FAILD";

export {
  SIGN_IN_WITH_PHONE_SSO_ACTION,
  SIGN_IN_WITH_PHONE_SSO_STARTED,
  SIGN_IN_WITH_PHONE_SSO_SUCCEED,
  SIGN_IN_WITH_PHONE_SSO_FAILD,
  VERIFY_WITH_PHONE_SSO_ACTION,
  VERIFY_WITH_PHONE_SSO_STARTED,
  VERIFY_WITH_PHONE_SSO_SUCCEED,
  VERIFY_WITH_PHONE_SSO_FAILD
};
