const GET_CARDS_ACTION = "GET_CARDS_ACTION";
const GET_CARDS_STARTED = "GET_CARDS_STARTED";
const GET_CARDS_SUCCEED = "GET_CARDS_SUCCEED";
const GET_CARDS_FAILD = "GET_CARDS_FAILD";

const GO_TO_CARD_LIST_ACTION = "GO_TO_CARD_LIST_ACTION";
const GO_TO_CARD_LIST_SUCCEED = "GO_TO_CARD_LIST_SUCCEED";

const SELECT_CARD_TO_BUY_ACTION = "SELECT_CARD_TO_BUY_ACTION";

const SUBMIT_INFORMATION_ACTION = "SUBMIT_INFORMATION_ACTION";

const CONFIRM_INFORMATION_ACTION = "CONFIRM_INFORMATION_ACTION";

const CONFIRM_CARD_STARTED = "CONFIRM_CARD_STARTED";
const CONFIRM_CARD_SUCCEED = "CONFIRM_CARD_SUCCEED";
const CONFIRM_CARD_FAILD = "CONFIRM_CARD_FAILD";

const SUBMIT_INFORMATION_STARTED = "SUBMIT_INFORMATION_STARTED";
const SUBMIT_INFORMATION_SUCCEED = "SUBMIT_INFORMATION_SUCCEED";
const SUBMIT_INFORMATION_FAILD = "SUBMIT_INFORMATION_FAILD";

const CONFIRM_INFORMATION_STARTED = "CONFIRM_INFORMATION_STARTED";
const CONFIRM_INFORMATION_FAILD = "CONFIRM_INFORMATION_FAILD";
const CONFIRM_INFORMATION_SUCCESS = "CONFIRM_INFORMATION_SUCCESS";

const GET_PURCHASED_CARD_DATA_ACTION = "GET_PURCHASED_CARD_DATA_ACTION";
const GET_PURCHASED_CARD_DATA_STARTED = "GET_PURCHASED_CARD_DATA_STARTED"
const GET_PURCHASED_CARD_DATA_SUCCESS = "GET_PURCHASED_CARD_DATA_SUCCESS";
const GET_PURCHASED_CARD_DATA_FAILD = "GET_PURCHASED_CARD_DATA_FAILD";


export {
  GET_CARDS_ACTION,
  GET_CARDS_STARTED,
  GET_CARDS_SUCCEED,
  GET_CARDS_FAILD,
  GO_TO_CARD_LIST_ACTION,
  GO_TO_CARD_LIST_SUCCEED,
  SELECT_CARD_TO_BUY_ACTION,
  SUBMIT_INFORMATION_ACTION,
  CONFIRM_INFORMATION_ACTION,
  CONFIRM_CARD_STARTED,
  CONFIRM_CARD_SUCCEED,
  CONFIRM_CARD_FAILD,
  SUBMIT_INFORMATION_STARTED,
  SUBMIT_INFORMATION_SUCCEED,
  SUBMIT_INFORMATION_FAILD,
  CONFIRM_INFORMATION_STARTED,
  CONFIRM_INFORMATION_FAILD,
  CONFIRM_INFORMATION_SUCCESS,
  GET_PURCHASED_CARD_DATA_ACTION,
  GET_PURCHASED_CARD_DATA_STARTED,
  GET_PURCHASED_CARD_DATA_SUCCESS,
  GET_PURCHASED_CARD_DATA_FAILD
};
