const GET_CARDS_ACTION = "GET_CARDS_ACTION";
const GET_CARDS_STARTED = "GET_CARDS_STARTED";
const GET_CARDS_SUCCEED = "GET_CARDS_SUCCEED";
const GET_CARDS_FAILD = "GET_CARDS_FAILD";

const GO_TO_CARD_LIST_ACTION = "GO_TO_CARD_LIST_ACTION";
const GO_TO_CARD_LIST_SUCCEED = "GO_TO_CARD_LIST_SUCCEED";

const SELECT_CARD_TO_BUY_ACTION = "SELECT_CARD_TO_BUY_ACTION";

export {
  GET_CARDS_ACTION,
  GET_CARDS_STARTED,
  GET_CARDS_SUCCEED,
  GET_CARDS_FAILD,
  GO_TO_CARD_LIST_ACTION,
  GO_TO_CARD_LIST_SUCCEED,
  SELECT_CARD_TO_BUY_ACTION
};
