const GET_CARD_ACTION = "GET_CARD_ACTION";
const GET_CARD_STARTED = "GET_CARD_STARTED";
const GET_CARD_SUCCESS = "GET_SETTINGS_SUCCESS";
const GET_CARD_FAILD = "GET_CARD_FAILD";
export { GET_CARD_ACTION, GET_CARD_STARTED, GET_CARD_SUCCESS, GET_CARD_FAILD };
