const GENERAL_SETTINGS_REQUEST = "/settings/general";
const SIGN_IN_WITH_PHONE_REQUEST = "/sso/check-operator";
const VERIFY_WITH_PHONE_REQUEST = "/sso/verify";
const CARDS_INDEX_REQUEST = "/card";
const CARDS_CREATE_REQUEST = "/card/create";

export {
  GENERAL_SETTINGS_REQUEST,
  SIGN_IN_WITH_PHONE_REQUEST,
  CARDS_INDEX_REQUEST,
  VERIFY_WITH_PHONE_REQUEST,
  CARDS_CREATE_REQUEST
};
