const START_APP = "START_APP";
const GET_SETTING_STARTED = "GET_SETTING_STARTED";
const GET_SETTINGS_SUCCEED = "GET_SETTINGS_SUCCESS";
const GET_SETTINGS_FAILD = "GET_SETTINGS_SUCCESS";
export {
  START_APP,
  GET_SETTING_STARTED,
  GET_SETTINGS_SUCCEED,
  GET_SETTINGS_FAILD
};
